### ISSUE TITLE
Can't use "/" in event names

### ISSUE THREAD

**Issue by JadedCtrl** [HaikuArchives/Calendar#82] opened 2021-04-09 16:36 UTC
Probably because event filenames are derived from events' names― filenames should be sanitized.

**Comment by singhsanskar202** [comment] 2021-07-11 05:10
I want to work on this issue.

**Comment by pulkomandy** [comment] 2021-07-11 08:32
Hi, please go ahead and let us know about your progress!

**Comment by singhsanskar202** [comment] 2021-07-11 10:58
Yes sure.

**Comment by singhsanskar202** [comment] 2021-07-11 11:21
<img width="1230" alt="Screenshot 2021-07-11 at 4 44 57 PM" src="https://user-images.githubusercontent.com/72119253/125192883-83762900-e267-11eb-9dec-dbeebd8f6e71.png">
I am not getting what i have to correct here please tell.

**Comment by pulkomandy** [comment] 2021-07-11 11:29
- Find where the events are saved to files or loaded from files
- Currently, the event name is used as the file name
- This doesn't work if there is a / in the name, because / is used in file paths to separate compoments (directories and subdirectories)
- So, you will need to replace the / with some other character, or remove it, when generating the filename
- Make sure the "real" event name is still stored in the file and can be retrieved when loading the file back into the application

**Comment by singhsanskar202** [comment] 2021-07-11 13:07
ok thanks

**Comment by scottmc** [comment] 2021-07-11 19:37
Your solution may also handle swapping characters such as ' " : ; # ? * = $ < > space tab and any other characters that may cause trouble in a filename.  Consider swapping them with a -
Also, as pointed out above, be sure to save original event name, just not in the filename.

**Comment by JadedCtrl** [comment] 2021-07-11 19:47
It looks like event names are saved in a file attribute, "Event:name", alongside the filename― not sure which is used for actually loading names though.

**Comment by singhsanskar202** [comment] 2021-07-12 04:14
<img width="1281" alt="Screenshot 2021-07-12 at 9 40 30 AM" src="https://user-images.githubusercontent.com/72119253/125229880-48223b80-e2f5-11eb-9765-690a59b15dce.png">
I have updated the event name by removing all the special characters in it. Will this work.

**Comment by pulkomandy** [comment] 2021-07-12 07:05
I think your code does not compile for several syntax problems. If you want to work on this issue, I suggest to set up a development environment with the Haiku operating system so you can compile and test your changes.

**Comment by fritzvd** [comment] 2021-07-25 20:32
@singhsanskar202 do you need any help with setting up a working environment or with working on a solution? I think a RegEx that swaps out special character to _underscores_ would work best.

**Comment by fritzvd** [comment] 2021-07-26 15:13
I've been trying to figure out what's going on to help out @singhsanskar202 . But can't seem to reproduce the error.
![rtSCDh6](https://user-images.githubusercontent.com/160328/127013428-7f92b7ba-dbb6-4e24-a558-f424976f2d61.png)

@JadedCtrl mentions files, but it seems all events are saved in a sqlite3 database. Am I correct in assuming this? I was thinking of adding a function GetSanitizedName() to the model, but not sure if that is the way to go.

**Comment by pulkomandy** [comment] 2021-07-26 15:19
You are right, the events where moved to a database and I think that fixed this problem?

**Comment by JadedCtrl** [comment] 2021-07-26 15:29
@fritzvd Are you using the version in HaikuPorts? Calendar was moved from using SQLite for storing events to queriable files a few months ago (around dc9d504). The HaikuPorts version hasn't been updated (no version bump), so it's still using SQLite.

The SQLite DB manager (src/db/SQLiteManager) is now only used for migrating pre-QueryDB verisions over to it (src/db/QueryDBManager).

**Comment by fritzvd** [comment] 2021-07-26 16:47
Ok. Thanks. Wasn't able to run the source yet. So I tried the Depot version. Anyways, I was trying to build the source but I'm running into a unforeseen problem. It takes FOREVER to install the sqlite_devel package? Anyone know what's up with that?

**Comment by pulkomandy** [comment] 2021-07-26 16:49
The software repository was offline earlier today, but it should be fixed now.

**Comment by fritzvd** [comment] 2021-07-26 19:00
I think I fixed it. see #83

**Comment by scottmc** [comment] 2021-11-03 15:50
Fixed by #96

**Closed as completed by scottmc** 2021-11-03 15:50 UTC
